### ISSUE TITLE
ANN: meetup for APS March meeting at San Antonio

### ISSUE THREAD

**Issue by i2000s** [JuliaQuantum/JuliaQuantum.github.io#18]
The annual March Meeting of the American Physical Society is on the way from March 2-6 in San Antonio, and our friends Katharine Hyatt and many others will be there. In case any Julia users would be interested in getting together there to chat for a bit, [here is the Doodle poll](http://doodle.com/sesc55rsd8hd59ag). A post on Julia-users group is also [alive](https://groups.google.com/forum/#!topic/julia-users/2rqxOq_wkCE) :-)  

Have a nice Julia-flavored conference!

**Comment by garrison** [comment]
The plan is to meet outside room 007A on Thursday (March 5) at 5:30pm and then walk to dinner somewhere together.  Feel free to join us if you are around!
