### ISSUE TITLE
ANN: Berkeley meetup videos online now

### ISSUE THREAD

**Issue by i2000s** [JuliaQuantum/JuliaQuantum.github.io#19]
Check out this [news](http://juliaquantum.github.io/news/2015/03/berkeley-meetup-videos-online/index.html) for videos and slides.  Feel free to spread the word. Thanks! 

Ref: #15

**Comment by philipithomas** [comment]
Wooho! Thanks for hosting. 

Here's the post on our blog about it: [https://blog.staffjoy.com/2015/03/02/julia-quantum/](https://blog.staffjoy.com/2015/03/02/julia-quantum/_
