### ISSUE TITLE
IRC room?

### ISSUE THREAD

**Issue by garrison** [JuliaQuantum/JuliaQuantum.github.io#22]
Hi everyone,

As things move forward I was thinking it might be good to have an IRC room for more casual conversations.  I created the room `#juliaquantum` on FreeNode for this purpose.  Webchat link is here: http://webchat.freenode.net/?channels=%23juliaquantum

**Comment by jiahao** [comment]
There is also Gitter.im, which some other organizations like BioJulia use.

**Comment by acroy** [comment]
@garrison That's a great idea. Thanks for setting it up.

I haven't tried Gitter.im, but it also looks interesting since it integrates into github.

**Comment by i2000s** [comment]
Sorry for the late response. I like the idea, and actually prefer to use Gitter. @amitjamadagni and a few others and I have been using it for JuliaQuantum chats. If there are more supports, a gitter sidebar can be embedded to the website by this weekend or so. See [demo](https://sidecar.gitter.im/).

**Comment by amitjamadagni** [comment]
@i2000s we have a room for JuliaQuantum on gitter. I guess we had the post GSoC 2015 meeting there.   The problem is adding people to the gitter room, I guess as of now only members can be added and there is a limit that a particular room can accommodate if it is not under a specific plan. Also I tried adding Roger long time back, but then it did not work :( may be there is some configuration problem. Also I just saw the sidebar and it looks great :) could we decentralize the sidebar for projects under JuliaQuantum ?!

**Comment by i2000s** [comment]
@amitjamadagni The JuliaQuantum room was set as a "shared room with JuliaQuantum members" only. To invite people outside of the org to that room **will require the creator of the room to change the setting**. Sorry, I added you to the GitterHQ room for testing, which is a public room. 

I propose to have a public room and then separate rooms for different projects if needed to be private. Overall, those can be integrated well into GitHub and websites.

**Comment by amitjamadagni** [comment]
:+1:  for idea of a common JuliaQuantum room, where we could have common meetings, package design decisions.
Also, :+1: for decentralized rooms for projects under JuliaQuantum, this would bring down the clutter on the main room and help people starting with the projects ! Please do let me know if I can do anything with respect to this.

**Comment by i2000s** [comment]
@amitjamadagni I don't know who created the JuliaQuantum room, can you help inform our discussion to the creator to see if it is acceptable to change the room to a public room? The public room may become lousy days off. Then you can add @garrison to the room as he started and cared about this discussion. If you have time, maybe you can also add the sidebar to our website. It's not a hard task. Thanks.

My recent schedule is to carefully read through your GSoC proposals and discussions this weekend and provide some feedback. We need the decision from @acroy on his mentership to you and @Roger-luo and how to organize this event. I am not sure  if you guys have noticed the [idealist of the Julia's GSoC projects](http://julialang.org/soc/ideas-page.html)... I may have some time to follow up next week. By then, I think an IRC communication channel will be well-used.

**Comment by amitjamadagni** [comment]
@i2000s I guess every organization is given a free organization room, ref : https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms

**Comment by i2000s** [comment]
Good observation! The "YourOrg/chat" channel slogan shines my eyes.  We could use that, and make a button on the top-right corner?

**Comment by amitjamadagni** [comment]
@Qi I guess the organization room (that is currently the JuliaQuantum room on gitter) is only for organization members (implying the members from the github repo). So it wont be possible for new visitors to use the same room, and though we link it to the website it wont be of much help ! Sorry if I am missing something here !

**Comment by i2000s** [comment]
Yeah, we need a new public channel room may be called ***JuliaQuantum/Chat*** from the link you gave to me. Should this work?

```
For example you may wish to create YourOrg/chat as a public chat room. Channels can be public, private or inherit GitHub owner permissions.If you click on the Create a room button on the bottom left of the screen, you should easily be able to create a channel. 
```

**Comment by i2000s** [comment]
Following this line, I would have some time in the coming days to help do some networking thing. The big question is how can we reach out to more people for our projects? For using Gitter, who is going to chat with public people and how to manage it? Do we need emailing list or other communication tools? How should we manage the twitter account and so on. Any comments are appreciated. If no objection heard for a week, I would merge the Gitter button to the repo, anyone who can help chat with public can join it while you can mute the chat notification if none mentions you. 

@Jutho I think you are the chairman of the coming Gordon Workshop in July. I will most likely attend the workshop and conference in Massachusetts. Maybe we can talk on expanding JuliaQuantum to the quantum community with your help, and maybe other things in the near future, if you like... :smile:

**Comment by Jutho** [comment]
Sorry for being late to the party. I am indeed chair of the GRS (the research seminar associated to the GRC) and would certainly like to see some JuliaQuantum related applications, e.g. for a poster. I (urgently) have to start sending around some advertisement for the GRS, and JuliaQuantum was certainly going to be one of my advertisement channels.

**Comment by i2000s** [comment]
@Jutho This all sounds exciting :+1: @amitjamadagni has chatted with me and he can collect some materials for the poster. I will start another thread to keep track on this line :) Thanks!
