### ISSUE TITLE
Is there a design of the main structure for JuliaQuantum's libs?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaQuantum/JuliaQuantum.github.io#33]
To be specific, is there a structure for package relationship and dependencies,like API design standard or all packages can be separated? for example,should all the base type included in QuBase.jl and all Schrodinger equation solvers should be in QuDynamics.jl?

**Comment by acroy** [comment]
Yes, the idea would be to bundle common types/functions in some set of "base packages". In the beginning I would keep new types/functions in your package. If it turns out to be generally useful, we can include it in QuBase etc ...
