### ISSUE TITLE
A Poster for GRS

### ISSUE THREAD

**Issue by i2000s** [JuliaQuantum/JuliaQuantum.github.io#36]
Dear all,

Since @Jutho is the chair of this year's Gordon Research Seminar for Quantum Science and I will also very likely to attend it at the end of July in Massachusetts (see [earlier discussion](https://github.com/JuliaQuantum/JuliaQuantum.github.io/issues/22)), I am opening up this new thread to keep track of the progress of making a poster for the GRS and the associate Gordon Research Conference (~one week long exhibition) to disseminate JuliaQuantum's existing and ongoing projects :) I am not a proper person to lead this project, but thankfully @amitjamadagni can offer a hand to summarize our projects, based on our earlier correspondence. Yes, everyone is welcome, indeed invited, to contribute. Materials can go to the [Resources repo](https://github.com/JuliaQuantum/Resources) I suppose. Besides the poster, if you have any ideas on how to make this opportunity more awesome, please comment here. 

@amitjamadagni Can you also update our Roadmap documents as well to reflect the recent progress? Thanks!

Cheers,
Qi

**Comment by amitjamadagni** [comment]
<h3> JuliaQuantum : Julia libraries for Quantum Science and Technology 

<h4> Abstract 

JuliaQuantum is an umbrella organization aiming to support libraries of quantum science using Julia language. Currently, the following libraries are being supported by the organization 

* *QuBase.jl* : A base library which provides the basic constructs used in Quantum Mechanics.
* *QuDirac.jl* : Library for using Dirac notation to perform quantum mechanics computations.
* *QuDynamics.jl* : Library for solving dynamical equations in quantum mechanics.

The poster aims at presenting the current capabilities of these packages as well present the ongoing efforts to integrate packages which focus on Quantum Information, Symbolic Quantum Mechanics among others.

<h4> Long Description 

The poster aims at presenting the current functionality of the libraries of JuliaQuantum, and also present some features which would be integrated in the future.

* QuBase.jl

_Current Functionality_

The current version is based on v0.4 of Julia. The base library provides a container like constructs `QuArray` for state vectors, operators which are Julia arrays. This is the base layer and every other construct is supported on the top of this layer. Most of the features like norm, scale, dot among many others are imported from the base and have been defined for `QuArray`. This package also provides support to some special operators like creation, annihilation, squeezing operators, the pauli matrices among others. 

_Features to be integrated_    

In the recent past, there has been a lot of discussion on the improving the `QuArray` constructs to support a more general construct that would accommodate the information of basis. This would not only be helpful to the JuliaQuantum community but may also serve as a common base package to other packages which use Linear Algebra. Efforts to integrate sparse, parallel features into the present `QuArray` construct have also been discussed.

* *QuDynamics.jl*

_Current Functionality_

The current version is based on v0.4 of Julia. The package is aimed at providing a unified framework for solvers for solving Dynamical Equations in Quantum Mechanics. Various solvers have been integrated from packages like ODE.jl, ExpmV.jl, Expokit.jl, using base features from QuBase.jl. The following Dynamical Equations can be solved using this package :

* Schrodinger Equation
* Liouville von Neumann Equation
* Lindblad Master Equation

Using the following solvers :

* Euler Method, Crank-Nicholson Method, Krylov subspace Method
* ode45, ode78, ode23s which have been integrated from ODE.jl
* Two versions of expmv implementations from :
  * ExpmV.jl
  * Expokit.jl
* Quantum Monte-Carlo Wave Function Method is also supported.

_Features to be integrated_

The current version supports time independent equations and one of the priorities which is already a work in progress feature is to extend the support to time dependent equations. Also, one of the other  features is to extend the functionality of the package by adding new solvers.   

<h5> Future Directions 

The ongoing efforts include supporting a Quantum Computation and Information based package, Tensor Network based package, Symbolic Quantum package among others which are being discussed and hopefully in the near future we expect the above libraries to be supported by the JuliaQuantum community.   

@Qi I hope to expand upon these ideas, i.e., to add QuDirac and more detailing on the packages of the future ! Any thoughts would be helpful. Also, I hope to update the Roadmap soon to further detail the work of the past and future !

**Comment by i2000s** [comment]
@amitjamadagni I really appreciate you are working this out! All looks great to me. It is a good start, and I think you can finish the rest in time. @Jutho Is this appealing to you as well? Please comment on the timeline and how we can deliver JuliaQuantum to the Gordon Workshop/Conference :)

@JuliaQuantum/juliaquantum As JuliaQuantum are seeking for a working mechanism that can efficiently gather more people working on Julia libraries for quantum sci and tech as a broad collaboration, the Roadmap docs have obviously served as a window for outsiders to find out what is happening in the org. If you can, please help @amitjamadagni update the Roadmap docs and this poster for finished milestones and up-coming events/plans/wishlists for the next 1-year cycle. Once this routine of summarizing and planning is proven to be a good thing to do for the org, a lot of things will be easier to achieve...
