### ISSUE TITLE
[Announcement] Use the Quantum tag on discourse.julialang.org

### ISSUE THREAD

**Issue by i2000s** [JuliaQuantum/JuliaQuantum.github.io#41]
If you use the official [Discourse forum](https://discourse.julialang.org/) of JuliaLang, feel free to use the magic [***Quantum***](https://discourse.julialang.org/tags/quantum) tag to group posts related to JuliaQuantum or quantum science. Just to let you know [vchuravy](http://discourse.julialang.org/users/vchuravy) created this tag for us a couple of days ago. 

Cheers,
Qi

**Comment by amitjamadagni** [comment]
#43 closing this !
