### ISSUE TITLE
Update JuliaQuantum website.

### ISSUE THREAD

**Issue by i2000s** [JuliaQuantum/JuliaQuantum.github.io#9]
As we are finishing up the initiative phase of the organization, we are ready to switch our gear to employ our website to power the development of our real projects. All the links connected to long discussions of organizational issues will gradually fade out from our website, instead, we will have more vivid content to attract people in/outside of Julia community to use and develop our libraries and forge a healthy eco-system for our organization. I will work on a dev branch of the website during the winter break. Fancy style of webpages or beautifying works are open to everyone. The dev branch will be merged to the master branch when the [QuBase.jl]( https://github.com/JuliaQuantum/QuBase.jl) repo is filled with enough functions. 

A brief summary of content to be updated (in progress):

* Using a style as close as to JuliaLang.org. Try employing Jekyll to power the website on GitHub. 
 
* New description of our organization and mission.

* Project page and links to related documents.

* People and contact information page (steering team, academic committee and so on).

* Friend-organizations...

Suggestions, artworks (like a new logo) and related ideas can be posted here. Supporting institutes and individuals will be acknowledged on the website as well. Correct me if any information present online is not precise.

**Comment by Travis-S** [comment]
What about taking 1.2 and removing the bra? It would seem to suggest Julia "acts" on quantum which would be pretty cute.

**Comment by i2000s** [comment]
@Travis-S +1
![juliaquantum_blackket](https://cloud.githubusercontent.com/assets/3915003/5690311/ce6d6066-983d-11e4-9689-8a616d4b7c99.png)

**Comment by i2000s** [comment]
The initialization of the Jekyll version of our website has been staged just now. If you have time, please take a look at the dev-jekyll branch of this repo. You may need to install Jekyll to preview the website. Another set of our logos can be found there--we need to decide which to use eventually. News, projects and community pages are created following the framework of the JuliaLang.github.com pages. I have filed a request for permission both to @StefanKarpinski earlier and the [julia-dev group](https://groups.google.com/forum/?fromgroups=#!topic/julia-dev/s9mxXwxi05w) today. Hopefully there is no problem to reuse their work for JuliaQuantum. In the mean time, feel free to edit and put more interesting contents over that branch. 

There are more work can be done for the website, like adding social-share buttons for posts, RSS feeds and so on. I need to work on the coming SQuINT workshop for now. Once our website and coordinating works got widely approved, I will organize and announce meetups among Julia community and academic institutes nearby Berkeley area. If you will, I appreciate any comments on the topics that can be highlighted during the [meetups](#12). 

Cheers,
Qi

**Comment by StefanKarpinski** [comment]
Love the logo!

**Comment by i2000s** [comment]
As you have noticed, [our website](http://juliaquantum.github.io) has been remodeled in Jekyll and styled kin to JuliaLang.org for a while! The major influence for us is that you can much easily push Github Flavored Markdown posts to appear on our website for updating project progresses. Let me know if there is anything I can make a quick improvement. 

One thing left for us to decide is the logo of JuliaQuantum. I have temparily used the logos I think most people would like following the comments above. There is only one small change on the text logo: the color of the ket sign has been changed to be brighter. Commit below if you prefer other alternatives. After this decision, I will upload the source files (a.k.a. the svg file) to the repo under MIT license as the Julia logo does to let everyone reuse them to make up project logos if you like. For example, the following one :-)

![qubase_logo_slim3_785x142](https://cloud.githubusercontent.com/assets/3915003/6772103/a2c60ecc-d0b9-11e4-8f0f-a93c83931d1d.png)

**Comment by i2000s** [comment]
Source code of logos uploaded. More source files of artworks can be requested to me whenever needed.
